---
Description: "This document is a sample configuration file that contains sample configurations for your spaces app."
app_local_path: apps
dependencies:
  - pyserini
  - faiss-cpu
  - torch
indices: "/Users/mac/Documents/castorini/pyserini/indexes/sample_collection_jsonl"
packages:
  - openjdk-11-jdk
page_icon: รฐ
space_sdk: streamlit
title: Pyserini
